version: '3.5'
services:
  hack_nginx:
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/ssl:/etc/nginx/ssl:ro
  hack_ui:
    volumes:
      - ./hackio-ui/:/usr/src/app
      - hackio_ui_modules:/usr/src/app/node_modules       
  hack_mysql:
    volumes:
      - mysql_data:/var/lib/mysql    
  hack_redis:
    volumes:
      - redis_data:/var/lib/redis
  hack_gatekeeper:
    volumes:
      - ./gatekeeper-ms/:/usr/src/app
      - gatekeeper_modules:/usr/src/app/node_modules
  hack_hackio:
      volumes:
      - ./hackio-ms/:/usr/src/app
      - hackio_modules:/usr/src/app/node_modules      
  hack_strapi:
    volumes:
      - ./strapi-ms/:/usr/src/app
      - strapi_modules:/usr/src/app/node_modules
  hack_gateway:
    volumes:
      - ./gateway-ms/:/usr/src/app
      - gateway_modules:/usr/src/app/node_modules
  hack_notify:
    volumes:
      - ./notify-ms/:/usr/src/app
      - notify_modules:/usr/src/app/node_modules
volumes:
  mysql_data:
    name: global_mysql
  strapi_modules:
    name: global_strapi
  gatekeeper_modules:
    name: global_gatekeeper
  gateway_modules:
    name: global_gateway
  redis_data:
    name: global_redis
  hackio_modules:
    name: global_hackio
  notify_modules:
    name: global_notify
  hackio_ui_modules:  
    name: global_ui
